name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      # - name: enable problem matcher
        # run: |
        #   echo "::add-matcher::.github/matcher.json"

      - name: setup revive
        uses: docker://morphy/revive-action:v2
        with:
          config: revive/config.toml
